Replace pypy with p314 (#233)
* Replace pypy with p314

* Fix lint

* Fix lint

---------

Co-authored-by: James Bensley <1025875+jwbensley@users.noreply.github.com>

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -23,10 +23,13 @@ jobs:
         run: |
           git config --global user.email "github_actions@example.com"
           git config --global user.name "Github Actions"
-      - name: Install Python 3.10
-        uses: actions/setup-python@v3
+      - name: Test SSH access to dnas_stats
+        run: |
+          ssh -T git@github.com 2>&1 | grep -q "successfully authenticated" && echo "SSH access verified" || echo "SSH access failed"
+      - name: Install Python 3.14
+        uses: actions/setup-python@v5
         with:
-          python-version: '3.10'
+          python-version: "3.14"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
@@ -35,4 +38,7 @@ jobs:
       - name: Run the tox tests
         working-directory: /home/runner/work/dfz_name_and_shame/dfz_name_and_shame/
         run: |
-            tox
+          tox
+        env:
+          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
+          SSH_AGENT_PID: ${{ env.SSH_AGENT_PID }}
